# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'package_dialog.ui'
#
# Created: Tue Nov  8 22:09:47 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(382, 310)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtGui.QSpacerItem(27, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.packageLabel = QtGui.QLabel(Dialog)
        self.packageLabel.setObjectName("packageLabel")
        self.gridLayout.addWidget(self.packageLabel, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(8, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 4, 1, 3)
        self.optionLabel = QtGui.QLabel(Dialog)
        self.optionLabel.setObjectName("optionLabel")
        self.gridLayout.addWidget(self.optionLabel, 0, 7, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 9, 1, 1)
        self.packageList = QtGui.QListView(Dialog)
        self.packageList.setObjectName("packageList")
        self.gridLayout.addWidget(self.packageList, 1, 0, 1, 4)
        self.optionList = QtGui.QListWidget(Dialog)
        self.optionList.setObjectName("optionList")
        self.gridLayout.addWidget(self.optionList, 1, 4, 1, 6)
        self.addPackageButton = QtGui.QPushButton(Dialog)
        self.addPackageButton.setMinimumSize(QtCore.QSize(30, 0))
        self.addPackageButton.setObjectName("addPackageButton")
        self.gridLayout.addWidget(self.addPackageButton, 2, 0, 1, 1)
        self.packagePlainText = QtGui.QPlainTextEdit(Dialog)
        self.packagePlainText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.packagePlainText.setObjectName("packagePlainText")
        self.gridLayout.addWidget(self.packagePlainText, 2, 1, 1, 2)
        self.removePackageButton = QtGui.QPushButton(Dialog)
        self.removePackageButton.setMinimumSize(QtCore.QSize(30, 0))
        self.removePackageButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.removePackageButton.setObjectName("removePackageButton")
        self.gridLayout.addWidget(self.removePackageButton, 2, 3, 1, 1)
        self.addOptionButton = QtGui.QPushButton(Dialog)
        self.addOptionButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.addOptionButton.setObjectName("addOptionButton")
        self.gridLayout.addWidget(self.addOptionButton, 2, 4, 1, 2)
        self.optionPlainText = QtGui.QPlainTextEdit(Dialog)
        self.optionPlainText.setMaximumSize(QtCore.QSize(16777215, 30))
        self.optionPlainText.setObjectName("optionPlainText")
        self.gridLayout.addWidget(self.optionPlainText, 2, 6, 1, 2)
        self.removeOptionButton = QtGui.QPushButton(Dialog)
        self.removeOptionButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.removeOptionButton.setObjectName("removeOptionButton")
        self.gridLayout.addWidget(self.removeOptionButton, 2, 8, 1, 2)
        spacerItem4 = QtGui.QSpacerItem(27, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(27, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 3, 3, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(21, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 3, 4, 1, 1)
        self.saveButton = QtGui.QPushButton(Dialog)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 3, 5, 1, 4)
        spacerItem7 = QtGui.QSpacerItem(21, 25, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 3, 9, 1, 1)
        self.cancelButton = QtGui.QPushButton(Dialog)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 3, 1, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.packageLabel.setText(QtGui.QApplication.translate("Dialog", "Packages", None, QtGui.QApplication.UnicodeUTF8))
        self.optionLabel.setText(QtGui.QApplication.translate("Dialog", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.addPackageButton.setText(QtGui.QApplication.translate("Dialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.removePackageButton.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.addOptionButton.setText(QtGui.QApplication.translate("Dialog", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.removeOptionButton.setText(QtGui.QApplication.translate("Dialog", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.saveButton.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

