# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created: Tue Nov  8 00:30:25 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 826)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuWindows = QtGui.QMenu(self.menubar)
        self.menuWindows.setObjectName("menuWindows")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.controlsDockWidget = QtGui.QDockWidget(MainWindow)
        self.controlsDockWidget.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.controlsDockWidget.setObjectName("controlsDockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previousPageButton = QtGui.QPushButton(self.dockWidgetContents)
        self.previousPageButton.setMaximumSize(QtCore.QSize(98, 16777215))
        self.previousPageButton.setObjectName("previousPageButton")
        self.horizontalLayout.addWidget(self.previousPageButton)
        self.pageSpinBox = QtGui.QSpinBox(self.dockWidgetContents)
        self.pageSpinBox.setEnabled(True)
        self.pageSpinBox.setFrame(True)
        self.pageSpinBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.pageSpinBox.setAccelerated(False)
        self.pageSpinBox.setMinimum(1)
        self.pageSpinBox.setProperty("value", 1)
        self.pageSpinBox.setObjectName("pageSpinBox")
        self.horizontalLayout.addWidget(self.pageSpinBox)
        self.maxPageLabel = QtGui.QLabel(self.dockWidgetContents)
        self.maxPageLabel.setObjectName("maxPageLabel")
        self.horizontalLayout.addWidget(self.maxPageLabel)
        self.nextPageButton = QtGui.QPushButton(self.dockWidgetContents)
        self.nextPageButton.setMinimumSize(QtCore.QSize(98, 0))
        self.nextPageButton.setMaximumSize(QtCore.QSize(98, 16777215))
        self.nextPageButton.setObjectName("nextPageButton")
        self.horizontalLayout.addWidget(self.nextPageButton)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.previousFindButton = QtGui.QPushButton(self.dockWidgetContents)
        self.previousFindButton.setEnabled(False)
        self.previousFindButton.setMaximumSize(QtCore.QSize(95, 16777215))
        self.previousFindButton.setObjectName("previousFindButton")
        self.horizontalLayout.addWidget(self.previousFindButton)
        self.searchLineEdit = QtGui.QLineEdit(self.dockWidgetContents)
        self.searchLineEdit.setEnabled(False)
        self.searchLineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout.addWidget(self.searchLineEdit)
        self.nextFindButton = QtGui.QPushButton(self.dockWidgetContents)
        self.nextFindButton.setEnabled(False)
        self.nextFindButton.setMaximumSize(QtCore.QSize(95, 16777215))
        self.nextFindButton.setObjectName("nextFindButton")
        self.horizontalLayout.addWidget(self.nextFindButton)
        self.clearButton = QtGui.QPushButton(self.dockWidgetContents)
        self.clearButton.setEnabled(False)
        self.clearButton.setMaximumSize(QtCore.QSize(45, 16777215))
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.scaleComboBox = QtGui.QComboBox(self.dockWidgetContents)
        self.scaleComboBox.setMinimumSize(QtCore.QSize(102, 0))
        self.scaleComboBox.setMaximumSize(QtCore.QSize(78, 16777215))
        self.scaleComboBox.setObjectName("scaleComboBox")
        self.scaleComboBox.addItem("")
        self.scaleComboBox.addItem("")
        self.scaleComboBox.addItem("")
        self.horizontalLayout.addWidget(self.scaleComboBox)
        self.scaleSpinBox = QtGui.QDoubleSpinBox(self.dockWidgetContents)
        self.scaleSpinBox.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.scaleSpinBox.setMinimum(0.0)
        self.scaleSpinBox.setMaximum(100.0)
        self.scaleSpinBox.setSingleStep(0.25)
        self.scaleSpinBox.setProperty("value", 1.0)
        self.scaleSpinBox.setObjectName("scaleSpinBox")
        self.horizontalLayout.addWidget(self.scaleSpinBox)
        self.controlsDockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.controlsDockWidget)
        self.annotationSourceDockWidget = QtGui.QDockWidget(MainWindow)
        self.annotationSourceDockWidget.setObjectName("annotationSourceDockWidget")
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName("dockWidgetContents_5")
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.annotationSourceTextEdit = QtGui.QTextEdit(self.dockWidgetContents_5)
        self.annotationSourceTextEdit.setObjectName("annotationSourceTextEdit")
        self.gridLayout_2.addWidget(self.annotationSourceTextEdit, 1, 0, 1, 1)
        self.compileButton = QtGui.QPushButton(self.dockWidgetContents_5)
        self.compileButton.setMinimumSize(QtCore.QSize(0, 97))
        self.compileButton.setMaximumSize(QtCore.QSize(20, 16777215))
        self.compileButton.setObjectName("compileButton")
        self.gridLayout_2.addWidget(self.compileButton, 1, 1, 1, 1)
        self.annotationSourceDockWidget.setWidget(self.dockWidgetContents_5)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.annotationSourceDockWidget)
        self.annotationDockWidget = QtGui.QDockWidget(MainWindow)
        self.annotationDockWidget.setMinimumSize(QtCore.QSize(200, 53))
        self.annotationDockWidget.setObjectName("annotationDockWidget")
        self.dockWidgetContents_6 = QtGui.QWidget()
        self.dockWidgetContents_6.setObjectName("dockWidgetContents_6")
        self.gridLayoutAnnotationDock = QtGui.QGridLayout(self.dockWidgetContents_6)
        self.gridLayoutAnnotationDock.setObjectName("gridLayoutAnnotationDock")
        self.annotationWidget = QtGui.QWidget(self.dockWidgetContents_6)
        self.annotationWidget.setObjectName("annotationWidget")
        self.gridLayoutAnnotationDock.addWidget(self.annotationWidget, 0, 0, 1, 1)
        self.annotationDockWidget.setWidget(self.dockWidgetContents_6)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.annotationDockWidget)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionControls = QtGui.QAction(MainWindow)
        self.actionControls.setCheckable(True)
        self.actionControls.setChecked(True)
        self.actionControls.setObjectName("actionControls")
        self.actionAnnotationSource = QtGui.QAction(MainWindow)
        self.actionAnnotationSource.setCheckable(True)
        self.actionAnnotationSource.setChecked(True)
        self.actionAnnotationSource.setObjectName("actionAnnotationSource")
        self.actionAnnotation = QtGui.QAction(MainWindow)
        self.actionAnnotation.setCheckable(True)
        self.actionAnnotation.setChecked(True)
        self.actionAnnotation.setObjectName("actionAnnotation")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionExport)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionQuit)
        self.menuWindows.addAction(self.actionControls)
        self.menuWindows.addAction(self.actionAnnotationSource)
        self.menuWindows.addAction(self.actionAnnotation)
        self.menu_Help.addAction(self.actionAbout)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuWindows.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWindows.setTitle(QtGui.QApplication.translate("MainWindow", "&Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.controlsDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.previousPageButton.setText(QtGui.QApplication.translate("MainWindow", "Previous page", None, QtGui.QApplication.UnicodeUTF8))
        self.maxPageLabel.setText(QtGui.QApplication.translate("MainWindow", "/ 1", None, QtGui.QApplication.UnicodeUTF8))
        self.nextPageButton.setText(QtGui.QApplication.translate("MainWindow", "Next page", None, QtGui.QApplication.UnicodeUTF8))
        self.previousFindButton.setText(QtGui.QApplication.translate("MainWindow", "Find previous", None, QtGui.QApplication.UnicodeUTF8))
        self.nextFindButton.setText(QtGui.QApplication.translate("MainWindow", "Find next", None, QtGui.QApplication.UnicodeUTF8))
        self.clearButton.setText(QtGui.QApplication.translate("MainWindow", "&Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Use scale", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Fit to width", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Fit to height", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationSourceDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Annotation Source", None, QtGui.QApplication.UnicodeUTF8))
        self.compileButton.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.annotationDockWidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "&Save a copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "&Export", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionControls.setText(QtGui.QApplication.translate("MainWindow", "&Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnnotationSource.setText(QtGui.QApplication.translate("MainWindow", "Annotation &Source", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnnotation.setText(QtGui.QApplication.translate("MainWindow", "&Annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))

